"""added tasks table

Revision ID: 2d039bfaa689
Revises: 568d74077e20
Create Date: 2015-05-05 01:41:25.956077

"""

# revision identifiers, used by Alembic.
revision = '2d039bfaa689'
down_revision = '568d74077e20'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tasks',
        sa.Column('name', 
            sa.String(
                length=255
            ), 
            nullable=False
        ),
        sa.Column('project_id', 
            sa.Integer(), 
            nullable=True
        ),
        sa.Column('subject', 
            sa.String(
                length=500
            ), 
            nullable=True
        ),
        sa.Column('content', 
            sa.Text(), 
            nullable=True
        ),
        sa.Column('due_date', 
            sa.DateTime(),
            nullable=True
        ),
        sa.Column('id', 
            sa.Integer(), 
            nullable=False
        ),
        sa.ForeignKeyConstraint(
            ['project_id'], 
            ['projects.id'], 
        ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint(
            'name', 
            'project_id'
        )
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tasks')
    ### end Alembic commands ###
