"""adding emails table and users.emails and users._password_hash

Revision ID: 511225667a1c
Revises: 2371a6d11a7d
Create Date: 2015-05-04 12:17:27.096152

"""

# revision identifiers, used by Alembic.
revision = '511225667a1c'
down_revision = '2371a6d11a7d'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql.expression import table,column
from bcrypt import hashpw,gensalt

pw = lambda data: hashpw(data,gensalt())

def add_admin_user():
    stmt = table('users',
            column('username'),
            column('_password_hash')).insert().\
                values\
                  (
                    username=sa.bindparam('username'),
                    _password_hash=sa.bindparam('_password_hash'),
                  )
    op.get_bind().execute(stmt,[dict(username='admin',_password_hash=pw('admin'))])



def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('emails',
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column(u'users', sa.Column('_password_hash', sa.Text(), nullable=True))
    add_admin_user()
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'users', '_password_hash')
    op.drop_table('emails')
    ### end Alembic commands ###
