"""made emails.address unique

Revision ID: 568d74077e20
Revises: 511225667a1c
Create Date: 2015-05-04 15:33:52.103174

"""

# revision identifiers, used by Alembic.
revision = '568d74077e20'
down_revision = '511225667a1c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'emails', ['address'])
    ### end Alembic commands ###


def downgrade():
    pass
    ### commands auto generated by Alembic - please adjust! ###
    #op.drop_constraint(None, 'emails',type_='unique')
    ### end Alembic commands ###
